# Databricks notebook source
# COMMAND ----------
"""
MegaMart Databricks Capstone
Stage: 01 - Raw Data Ingestion

Purpose
-------
Load the CSV files generated by generate_sample_data.py into
Bronze Delta tables in Unity Catalog.

Responsibilities
----------------
1. Verify that all expected source files exist.
2. Read the CSV files as raw source data.
3. Add ingestion metadata.
4. Write each source dataset as a Bronze Delta table.
5. Print ingestion statistics.

Important
---------
This stage does NOT:
- clean data
- fix invalid values
- remove duplicates
- standardize formats
- apply business rules

Those activities belong to later pipeline stages.
"""

# COMMAND ----------

# =========================
# 1. Imports
# =========================

import sys
from pathlib import Path

from datetime import datetime, timezone

from pyspark.sql import functions as F

# ------------------------------------------------------------------
# 1a. Resolve project root
# ------------------------------------------------------------------
# Scripts live under scripts/<stage>/ while config/ and shared/ are
# at the project root.  Walk upward from this file's location to find
# the directory containing both config/project_config.py and
# shared/common.py, then add it to sys.path so the imports below work.
# ------------------------------------------------------------------

def _find_project_root() -> Path:
    here = (
        Path(__file__).resolve().parent
        if "__file__" in globals()
        else Path.cwd().resolve()
    )
    cwd = Path.cwd().resolve()
    candidates = [here, *here.parents, cwd, *cwd.parents]
    seen: set = set()
    for candidate in candidates:
        if candidate in seen:
            continue
        seen.add(candidate)
        if (candidate / "config" / "project_config.py").exists() and (
            candidate / "shared" / "common.py"
        ).exists():
            return candidate
    raise RuntimeError(
        "Could not locate project root containing "
        "config/project_config.py and shared/common.py. "
        "Run this file from the MegaMart-Capstone-1 Git folder."
    )


PROJECT_ROOT = _find_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from config.project_config import (  # noqa: E402
    RAW_VOLUME_PATH,
    SOURCE_FILES,
    BRONZE_TABLES,
)

from shared.common import create_run_id  # noqa: E402


# COMMAND ----------

# =========================
# 2. Pipeline Configuration
# =========================

PIPELINE_NAME = "megamart_pipeline"
STAGE_NAME = "01_ingestion"

RUN_ID = create_run_id(STAGE_NAME)

print(f"Pipeline : {PIPELINE_NAME}")
print(f"Stage    : {STAGE_NAME}")
print(f"Run ID   : {RUN_ID}")
print(f"Raw path : {RAW_VOLUME_PATH}")


# COMMAND ----------

# =========================
# 3. Build Source Paths
# =========================

source_paths = {
    dataset_name: f"{RAW_VOLUME_PATH}/{file_name}"
    for dataset_name, file_name in SOURCE_FILES.items()
}

print("\n=== Source Files ===")

for dataset_name, path in source_paths.items():
    print(f"{dataset_name:22s} -> {path}")


# COMMAND ----------

# =========================
# 4. Verify Source Files
# =========================

print("\n=== Checking Source Files ===")

missing_files = []

for dataset_name, path in source_paths.items():

    try:
        dbutils.fs.ls(path)
        print(f"✓ {dataset_name}: found")

    except Exception:
        missing_files.append(
            {
                "dataset": dataset_name,
                "path": path,
            }
        )

        print(f"✗ {dataset_name}: NOT FOUND")


if missing_files:

    missing_details = "\n".join(
        f"- {item['dataset']}: {item['path']}"
        for item in missing_files
    )

    raise FileNotFoundError(
        "\n"
        "One or more required source files are missing.\n\n"
        "Upload the generated CSV files to:\n"
        f"{RAW_VOLUME_PATH}\n\n"
        "Missing files:\n"
        f"{missing_details}\n"
    )

print("\nAll expected source files are available.")


# COMMAND ----------

# =========================
# 5. Expected Source Columns
# =========================
#
# These definitions come from generate_sample_data.py.
# We intentionally keep the actual generator schema here.

EXPECTED_COLUMNS = {

    "stores": [
        "store_id",
        "store_name",
        "location",
        "manager_name",
    ],

    "products": [
        "product_id",
        "product_name",
        "category",
        "unit_price",
        "supplier_id",
    ],

    "suppliers": [
        "supplier_id",
        "supplier_name",
        "contact_person",
        "phone",
    ],

    "sales_transactions": [
        "transaction_id",
        "store_id",
        "product_id",
        "quantity_sold",
        "unit_price",
        "total_amount",
        "sale_date",
    ],

    "inventory": [
        "inventory_id",
        "store_id",
        "product_id",
        "quantity_on_hand",
    ],

    "purchase_orders": [
        "po_id",
        "supplier_id",
        "order_date",
        "delivery_date",
    ],
}


# COMMAND ----------

# =========================
# 6. Validate Source Headers
# =========================

print("\n=== Validating Source Headers ===")

for dataset_name, path in source_paths.items():

    source_df = (
        spark.read
        .format("csv")
        .option("header", "true")
        .option("inferSchema", "false")
        .option("mode", "PERMISSIVE")
        .load(path)
    )

    actual_columns = source_df.columns
    expected_columns = EXPECTED_COLUMNS[dataset_name]

    if actual_columns != expected_columns:

        raise ValueError(
            f"""
Unexpected column structure in {SOURCE_FILES[dataset_name]}.

Expected:
{expected_columns}

Received:
{actual_columns}
"""
        )

    print(
        f"✓ {SOURCE_FILES[dataset_name]}: "
        "header validated"
    )


# COMMAND ----------

# =========================
# 7. Ingest to Bronze
# =========================

print("\n=== Starting Bronze Ingestion ===")

ingestion_results = []


for dataset_name, path in source_paths.items():

    bronze_table = BRONZE_TABLES[dataset_name]

    print("\n----------------------------------------")
    print(f"Dataset      : {dataset_name}")
    print(f"Source       : {path}")
    print(f"Bronze table : {bronze_table}")
    print("----------------------------------------")

    # Read source file without schema inference.
    # Bronze should preserve the source representation.
    df = (
        spark.read
        .format("csv")
        .option("header", "true")
        .option("inferSchema", "false")
        .option("mode", "PERMISSIVE")
        .load(path)
    )

    source_record_count = df.count()

    # Add technical metadata.
    bronze_df = (
        df
        .withColumn(
            "_source_file",
            F.lit(SOURCE_FILES[dataset_name]),
        )
        .withColumn(
            "_source_path",
            F.lit(path),
        )
        .withColumn(
            "_pipeline_name",
            F.lit(PIPELINE_NAME),
        )
        .withColumn(
            "_stage_name",
            F.lit(STAGE_NAME),
        )
        .withColumn(
            "_run_id",
            F.lit(RUN_ID),
        )
        .withColumn(
            "_ingestion_timestamp",
            F.current_timestamp(),
        )
    )

    # Write Bronze table.
    #
    # overwrite is intentional for this static capstone dataset.
    # Re-running the same ingestion does not append duplicate
    # Bronze copies.
    (
        bronze_df
        .write
        .format("delta")
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(bronze_table)
    )

    bronze_record_count = (
        spark.table(bronze_table).count()
    )

    ingestion_results.append(
        {
            "dataset": dataset_name,
            "source_records": source_record_count,
            "bronze_records": bronze_record_count,
            "bronze_table": bronze_table,
            "status": "SUCCESS",
        }
    )

    print(
        f"✓ Loaded {source_record_count:,} records "
        f"into {bronze_table}"
    )


# COMMAND ----------

# =========================
# 8. Ingestion Summary
# =========================

print("\n=== INGESTION SUMMARY ===")

for result in ingestion_results:

    print(
        f"{result['dataset']:22s} | "
        f"source={result['source_records']:>6,} | "
        f"bronze={result['bronze_records']:>6,} | "
        f"{result['status']}"
    )


# COMMAND ----------

# =========================
# 9. Verify Bronze Tables
# =========================

print("\n=== BRONZE TABLE VERIFICATION ===")

for dataset_name, bronze_table in BRONZE_TABLES.items():

    print("\n----------------------------------------")
    print(bronze_table)
    print("----------------------------------------")

    print("Schema:")

    spark.sql(
        f"DESCRIBE TABLE {bronze_table}"
    ).show(truncate=False)

    print("Sample records:")

    (
        spark.table(bronze_table)
        .limit(5)
        .show(truncate=False)
    )


# COMMAND ----------

# =========================
# 10. Final Status
# =========================

print("\n========================================")
print("Bronze ingestion completed successfully.")
print("========================================")

print(f"Run ID: {RUN_ID}")

print("\nBronze tables:")

for bronze_table in BRONZE_TABLES.values():
    print(f"✓ {bronze_table}")